### ISSUE TITLE
Error on docker-tropo

### ISSUE THREAD

**Issue by jabelk** [networkop/arista-network-ci#3]
Ran into the following errror, after suceeding on all previous steps:

```
(testdir) jabelk@jabelk-Meerkat:~/eos_containers/arista-network-ci/prod$ docker-topo --create topo.yml
INFO:__main__:Version 2 requires sudo. Restarting script with sudo
[sudo] password for jabelk: 
INFO:__main__:Container prod_Leaf-1 already running
INFO:__main__:Container prod_Leaf-2 already running
INFO:__main__:Container prod_Leaf-3 already running
INFO:__main__:Container prod_Spine-1 already running
INFO:__main__:Container prod_Spine-2 already running
Traceback (most recent call last):
  File "/home/jabelk/eos_containers/arista-network-ci/testdir/lib/python3.6/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/home/jabelk/eos_containers/arista-network-ci/testdir/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.35/containers/create?name=prod_Host-1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jabelk/eos_containers/arista-network-ci/testdir/bin/docker-topo", line 793, in <module>
    main()
  File "/home/jabelk/eos_containers/arista-network-ci/testdir/bin/docker-topo", line 733, in main
    started = [device.start() == 0 for (name, device) in devices.items()]
  File "/home/jabelk/eos_containers/arista-network-ci/testdir/bin/docker-topo", line 733, in <listcomp>
    started = [device.start() == 0 for (name, device) in devices.items()]
  File "/home/jabelk/eos_containers/arista-network-ci/testdir/bin/docker-topo", line 437, in start
    super().start(*args, **kwargs)
  File "/home/jabelk/eos_containers/arista-network-ci/testdir/bin/docker-topo", line 311, in start
    self._get_or_create()
  File "/home/jabelk/eos_containers/arista-network-ci/testdir/bin/docker-topo", line 278, in _get_or_create
    self.container = self._create()
  File "/home/jabelk/eos_containers/arista-network-ci/testdir/bin/docker-topo", line 298, in _create
    tty=True
  File "/home/jabelk/eos_containers/arista-network-ci/testdir/lib/python3.6/site-packages/docker/models/containers.py", line 843, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/jabelk/eos_containers/arista-network-ci/testdir/lib/python3.6/site-packages/docker/api/container.py", line 427, in create_container
    return self.create_container_from_config(config, name)
  File "/home/jabelk/eos_containers/arista-network-ci/testdir/lib/python3.6/site-packages/docker/api/container.py", line 438, in create_container_from_config
    return self._result(res, True)
  File "/home/jabelk/eos_containers/arista-network-ci/testdir/lib/python3.6/site-packages/docker/api/client.py", line 262, in _result
    self._raise_for_status(response)
  File "/home/jabelk/eos_containers/arista-network-ci/testdir/lib/python3.6/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/jabelk/eos_containers/arista-network-ci/testdir/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: alpine-host:latest")

```

running on ubuntu 18.04, with the following docker images and ps

```
(testdir) jabelk@jabelk-Meerkat:~/eos_containers/arista-network-ci/prod$ docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
batfish                     latest              6afe0fb1fe08        13 hours ago        987MB
172.17.0.1:5000/ceos        4.20.0F             294502a583e2        13 hours ago        1.35GB
ceos                        4.20.0F             294502a583e2        13 hours ago        1.35GB
gitlab/gitlab-runner        latest              f6b9a594dd78        14 hours ago        389MB
172.17.0.1:5000/networkci   latest              de08f5e3eeec        26 hours ago        691MB
networkci                   latest              de08f5e3eeec        26 hours ago        691MB
ceos                        latest              20db9c40d67d        29 hours ago        1.35GB
docker                      stable-dind         07a1fe9503d8        5 days ago          181MB
gitlab/gitlab-ce            latest              399829d2ce89        11 days ago         1.56GB
registry                    latest              33fbbf4a24e5        12 days ago         24.2MB
ubuntu                      16.04               b0ef3016420a        2 weeks ago         117MB
vr-csr                      16.06.01            6b39c8f56752        11 months ago       1.87GB
vr-csr                      16.04.01            5120b15b4ecb        11 months ago       1.76GB
vr-bgp                      latest              b88129b200e9        11 months ago       641MB
vr-xcon                     latest              31db6abbeb01        11 months ago       147MB
vrnetlab/vr-xcon            latest              4aab73a84fa0        12 months ago       147MB
debian                      stable              e03ce33c6fd7        13 months ago       100MB
(testdir) jabelk@jabelk-Meerkat:~/eos_containers/arista-network-ci/prod$ docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                  PORTS                                                                         NAMES
0cdcaa31a802        ceos:4.20.0F                  "/sbin/init"             12 hours ago        Up 12 hours             0.0.0.0:8004->443/tcp                                                         prod_Spine-2
613de867eaeb        ceos:4.20.0F                  "/sbin/init"             12 hours ago        Up 12 hours             0.0.0.0:8003->443/tcp                                                         prod_Spine-1
7863edd8ed4a        ceos:4.20.0F                  "/sbin/init"             12 hours ago        Up 12 hours             0.0.0.0:8002->443/tcp                                                         prod_Leaf-3
a51d7c072e8c        ceos:4.20.0F                  "/sbin/init"             12 hours ago        Up 12 hours             0.0.0.0:8001->443/tcp                                                         prod_Leaf-2
48eada18a48d        ceos:4.20.0F                  "/sbin/init"             12 hours ago        Up 12 hours             0.0.0.0:8000->443/tcp                                                         prod_Leaf-1
6d2ad939861d        registry                      "/entrypoint.sh /etc…"   13 hours ago        Up 13 hours             0.0.0.0:5000->5000/tcp                                                        gitlab-registry
7204355bde78        gitlab/gitlab-runner:latest   "/usr/bin/dumb-init …"   13 hours ago        Up 13 hours                                                                                           runner-lab
0405ffabe594        batfish                       "/bin/bash -c 'cd ba…"   13 hours ago        Up 13 hours             0.0.0.0:9996-9998->9996-9998/tcp                                              gitlab-batfish
523d8fed632d        gitlab/gitlab-ce:latest       "/assets/wrapper"        13 hours ago        Up 13 hours (healthy)   80/tcp, 0.0.0.0:9080->9080/tcp, 0.0.0.0:9022->22/tcp, 0.0.0.0:9443->443/tcp   gitlab-lab
(testdir) jabelk@jabelk-Meerkat:~/eos_containers/arista-network-ci/prod
```

**Comment by jabelk** [comment]
google searching seems to correlate ansible + docker causing issue, but was hoping you might have seen it before.

**Comment by networkop** [comment]
yes, i have. i wonder how that slipped through the cracks. alpine-host is a special-purpose alpine image I've built to simulate end hosts.  
https://github.com/networkop/docker-topo/tree/master/topo-extra-files/host
I have a pre-built image on dockerhub which should have been downloaded at this step:
```
lab_testing:
  stage: test
  before_script:
  - docker image pull networkop/alpine-host:latest
  - docker image tag networkop/alpine-host alpine-host
```
Can you check your logs prior to that? Maybe you dind't have internet access?

Note that since you're running dind, what you have on your host OS (e.g. docker images) doesn't matter, all images should be present/accessible from inside the runner's container. You can add "docker images" step to the before_script and run it just before `docker-topo --create` to see what's in your dind image library.

**Comment by jasonserpent** [comment]
Hi,
One thing you seem to be missing is the alpine container.

“docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: alpine-host:latest")”

Try adding that and rerun.

Cheers

Pete

**Comment by jabelk** [comment]
That seemed to work! 

I just manually ran the docker image pull and tag commands in bash. Having some other issues, but will play around  with a bit before I open another issue. 
fyi
```
(testdir) jabelk@jabelk-Meerkat:~/eos_containers/arista-network-ci/prod$ docker image pull networkop/alpine-host:latest
latest: Pulling from networkop/alpine-host
4fe2ade4980c: Pull complete 
82164efab16d: Pull complete 
85051ecabe1f: Pull complete 
050f0114e877: Pull complete 
9d134ff4f6e8: Pull complete 
Digest: sha256:92dbb3ab65b7697eff983e513d6472dcd805c8c3b48b94c837e55b6d4f3e1671
Status: Downloaded newer image for networkop/alpine-host:latest
(testdir) jabelk@jabelk-Meerkat:~/eos_containers/arista-network-ci/prod$ docker image tag networkop/alpine-host alpine-host
(testdir) jabelk@jabelk-Meerkat:~/eos_containers/arista-network-ci/prod$ docker-topo --create topo.yml
INFO:__main__:Version 2 requires sudo. Restarting script with sudo
[sudo] password for jabelk: 
INFO:__main__:Container prod_Leaf-1 already running
INFO:__main__:Container prod_Leaf-2 already running
INFO:__main__:Container prod_Leaf-3 already running
INFO:__main__:Container prod_Spine-1 already running
INFO:__main__:Container prod_Spine-2 already running
INFO:__main__:
alias Leaf-1='docker exec -it prod_Leaf-1 Cli'
alias Leaf-2='docker exec -it prod_Leaf-2 Cli'
alias Leaf-3='docker exec -it prod_Leaf-3 Cli'
alias Spine-1='docker exec -it prod_Spine-1 Cli'
alias Spine-2='docker exec -it prod_Spine-2 Cli'
alias Host-1='docker exec -it prod_Host-1 sh'
alias Host-11='docker exec -it prod_Host-11 sh'
alias Host-2='docker exec -it prod_Host-2 sh'
alias Host-3='docker exec -it prod_Host-3 sh'
INFO:__main__:Devices have not been started
WARNING:pyroute2.ipdb.main:shutdown in progress
(testdir) jabelk@jabelk-Meerkat:~/eos_containers/arista-network-ci/prod$ docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED              STATUS                PORTS                                                                         NAMES
1ed83e52b21d        alpine-host:latest            "/home/alpine/entryp…"   About a minute ago   Up About a minute                                                                                   prod_Host-3
2c2b0812b295        alpine-host:latest            "/home/alpine/entryp…"   About a minute ago   Up About a minute                                                                                   prod_Host-2
5c802161c9d7        alpine-host:latest            "/home/alpine/entryp…"   About a minute ago   Up About a minute                                                                                   prod_Host-11
83389c86eede        alpine-host:latest            "/home/alpine/entryp…"   About a minute ago   Up About a minute                                                                                   prod_Host-1
0cdcaa31a802        ceos:4.20.0F                  "/sbin/init"             3 days ago           Up 3 days             0.0.0.0:8004->443/tcp                                                         prod_Spine-2
613de867eaeb        ceos:4.20.0F                  "/sbin/init"             3 days ago           Up 3 days             0.0.0.0:8003->443/tcp                                                         prod_Spine-1
7863edd8ed4a        ceos:4.20.0F                  "/sbin/init"             3 days ago           Up 3 days             0.0.0.0:8002->443/tcp                                                         prod_Leaf-3
a51d7c072e8c        ceos:4.20.0F                  "/sbin/init"             3 days ago           Up 3 days             0.0.0.0:8001->443/tcp                                                         prod_Leaf-2
48eada18a48d        ceos:4.20.0F                  "/sbin/init"             3 days ago           Up 3 days             0.0.0.0:8000->443/tcp                                                         prod_Leaf-1
6d2ad939861d        registry                      "/entrypoint.sh /etc…"   3 days ago           Up 3 days             0.0.0.0:5000->5000/tcp                                                        gitlab-registry
7204355bde78        gitlab/gitlab-runner:latest   "/usr/bin/dumb-init …"   3 days ago           Up 3 days                                                                                           runner-lab
0405ffabe594        batfish                       "/bin/bash -c 'cd ba…"   3 days ago           Up 3 days             0.0.0.0:9996-9998->9996-9998/tcp                                              gitlab-batfish
523d8fed632d        gitlab/gitlab-ce:latest       "/assets/wrapper"        3 days ago           Up 3 days (healthy)   80/tcp, 0.0.0.0:9080->9080/tcp, 0.0.0.0:9022->22/tcp, 0.0.0.0:9443->443/tcp   gitlab-lab
(testdir) jabelk@jabelk-Meerkat:~/eos_containers/arista-network-ci/prod$ 
```

**Comment by networkop** [comment]
cool man, don't  hesitate to open issues, even if it's seems obvious. it may help others who run into similar issues.

**Comment by networkop** [comment]
btw, the error you're getting is because you tried to start the topology twice. in these cases, it's best to run `--destroy` once, followed by another `--create`
